// Code generated by tlex. DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
)

var nc = 0
var nw = 0
var nl = 0

type yyStateID = int
type yyRegexID = int

var YYText string

var (
	ErrYYScan = errors.New("failed to scan")
)

// state id to regex id
var yyStateIDToRegexID = []yyRegexID{
	0, // state 0 is dead state
	1,
	1,
	3,
	2,
	1,
}

var yyFinStates = map[yyStateID]struct{}{
	0: {},
	1: {},
	2: {},
	3: {},
	4: {},
	5: {},
}

type yyinterval struct {
	l int
	r int
}

func (x yyinterval) overlap(y yyinterval) bool {
	return y.l <= x.r && x.l <= y.r
}

var yyTransitionTable = map[yyStateID]map[yyinterval]yyStateID{
	1: {
		yyinterval{l: 0, r: 8}:        4,
		yyinterval{l: 9, r: 9}:        2,
		yyinterval{l: 10, r: 10}:      3,
		yyinterval{l: 11, r: 12}:      4,
		yyinterval{l: 13, r: 13}:      2,
		yyinterval{l: 14, r: 31}:      4,
		yyinterval{l: 32, r: 32}:      5,
		yyinterval{l: 33, r: 1114111}: 4,
	},
	2: {
		yyinterval{l: 9, r: 9}:        2,
		yyinterval{l: 11, r: 12}:      4,
		yyinterval{l: 13, r: 13}:      2,
		yyinterval{l: 14, r: 31}:      4,
		yyinterval{l: 32, r: 32}:      5,
		yyinterval{l: 33, r: 1114111}: 4,
		yyinterval{l: 0, r: 8}:        4,
	},
	4: {
		yyinterval{l: 14, r: 31}:      4,
		yyinterval{l: 33, r: 1114111}: 4,
		yyinterval{l: 0, r: 8}:        4,
		yyinterval{l: 9, r: 9}:        4,
		yyinterval{l: 11, r: 12}:      4,
		yyinterval{l: 13, r: 13}:      4,
	},
	5: {
		yyinterval{l: 9, r: 9}:   5,
		yyinterval{l: 13, r: 13}: 5,
		yyinterval{l: 32, r: 32}: 5,
	},
}

func yyNextStep(id yyStateID, r rune) yyStateID {
	if mp, ok := yyTransitionTable[id]; ok {
		t := yyinterval{l: int(r), r: int(r)}
		for intv, sid := range mp {
			if intv.overlap(t) {
				return sid
			}
		}
	}

	return 0
}

type yyLexer struct {
	rs          RuneReadSeeker
	beginPos    int
	finPos      int
	currPos     int
	finRegexID  int
	currStateID yyStateID
	YYText      string
}

type RuneReadSeeker interface {
	io.ReadSeeker
	io.RuneScanner
}

func New(rs RuneReadSeeker) *yyLexer {
	return &yyLexer{
		rs:          rs,
		beginPos:    0,
		finPos:      0,
		currPos:     0,
		finRegexID:  0,
		currStateID: 1, // init state id is 1.
	}
}

func (yylex *yyLexer) currRune() (rune, int, error) {
	ru, size, err := yylex.rs.ReadRune()
	if err != nil {
		return 0, 0, err
	}
	if err := yylex.rs.UnreadRune(); err != nil {
		return 0, 0, err
	}
	return ru, size, nil
}

func (yylex *yyLexer) Next() (int, error) {
	yyEofCnt := 0
yystart:
	for {
		yyr, yysize, err := yylex.currRune()
		if err != nil {
			if errors.Is(err, io.EOF) {
				yyEofCnt++
				if yyEofCnt == 1 {
					goto finProcess
				}
			}
			return 0, err
		}
	finProcess:
		yyNxStID := yyNextStep(yylex.currStateID, yyr)
		if yyNxStID == 0 {
			if _, err := yylex.rs.Seek(int64(yylex.finPos), io.SeekStart); err != nil {
				return 0, err
			}
			_, lastSize, err := yylex.currRune()
			if err != nil {
				return 0, err
			}
			yydata := make([]byte, yylex.finPos+lastSize-yylex.beginPos)
			if _, err := yylex.rs.Seek(int64(yylex.beginPos), io.SeekStart); err != nil {
				return 0, err
			}
			if _, err := yylex.rs.Read(yydata); err != nil {
				return 0, err
			}
			yylex.YYText = string(yydata)
			YYText = yylex.YYText
			yyNewCurrPos := yylex.finPos + lastSize
			yylex.beginPos = yyNewCurrPos
			yylex.finPos = yyNewCurrPos
			yylex.currPos = yyNewCurrPos
			yylex.currStateID = 1

			regexID := yylex.finRegexID
			yylex.finRegexID = 0
			switch regexID {
			case 0:
				return 0, ErrYYScan
			case 1:
				{
					nc++
				}
				goto yystart
			case 2:
				{
					nc += len([]rune(YYText))
					nw++
				}
				goto yystart
			case 3:
				{
					nl++
					nc++
				}
				goto yystart

			default:
				return 0, ErrYYScan
			}
		}
		if _, ok := yyFinStates[yyNxStID]; ok {
			yylex.finPos = yylex.currPos
			yylex.finRegexID = yyStateIDToRegexID[yyNxStID]
		}
		yylex.currStateID = yyNxStID
		yylex.currPos += yysize
		if _, err := yylex.rs.Seek(int64(yylex.currPos), io.SeekStart); err != nil {
			return 0, err
		}
	}

	return 0, io.EOF
}

// This part is optional
func main() {
	program := `hello world
hello tlex
あいう αβγ
`
	fmt.Print(program)
	fmt.Println("-----------------")

	lex := New(bytes.NewReader([]byte(program)))
	for {
		_, err := lex.Next()
		if err != nil {
			break
		}
	}
	fmt.Printf("number of lines: %d\n", nl)
	fmt.Printf("number of words: %d\n", nw)
	fmt.Printf("number of chars: %d\n", nc)
}
